In [1]:
cd E:\karthi_m\wind

E:\karthi_m\wind


In [2]:
import pandas as pd
from sklearn.model_selection import cross_val_score
from sklearn import metrics
import seaborn as sns
import numpy as np
from sklearn.metrics import accuracy_score

In [3]:
da=pd.read_csv('data1.csv')

In [4]:
da.head()

windspeed  airdensity  amb_temp  nac_direction blds_pitchangle  rtr_rpm  \
0        9.1    1.162127        27           61.8         (-2,-4)     14.1   
1        9.6    1.162127        27           61.8         (-2,-4)     14.4   
2        9.6    1.162127        27           61.8         (-2,-4)     14.4   
3       11.2    1.162127        27           65.2     (-0.1,-1.9)     14.5   
4       11.4    1.162127        27           66.6     (-0.1,-1.9)     14.5   

   gen_rpm wtg_state  
0   1305.0        ok  
1   1336.0        ok  
2   1330.0        ok  
3   1345.0        ok  
4   1344.0        ok

In [5]:
da['wtg_state'].value_counts()

ok                   44020
wind low              8658
curtailed             4186
Gen not conn          3896
high wind cut-out       29
Name: wtg_state, dtype: int64

In [6]:
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import LabelEncoder

In [7]:
y_ = da.apply(LabelEncoder().fit_transform)
y_.head()

windspeed  airdensity  amb_temp  nac_direction  blds_pitchangle  rtr_rpm  \
0         90           8         6            568                1      141   
1         95           8         6            568                1      144   
2         95           8         6            568                1      144   
3        111           8         6            602                0      145   
4        113           8         6            616                0      145   

   gen_rpm  wtg_state  
0     2805          3  
1     3036          3  
2     2982          3  
3     3124          3  
4     3114          3

In [8]:
x= da.drop(['wtg_state'],axis=1)
y= da['wtg_state']

In [9]:
x2=pd.get_dummies(x['blds_pitchangle'],drop_first=True)
x1=x.drop(['blds_pitchangle'],axis=1)
x= pd.concat([x1, x2], axis=1)

In [10]:
#naive bayes

In [11]:
from sklearn.model_selection import cross_val_score
from sklearn.naive_bayes import MultinomialNB
NB = MultinomialNB()

In [12]:
NB_scores = cross_val_score(NB, x, y, cv=6, scoring='accuracy')
NB_scores.mean()

0.6352356653825152

In [13]:
print(NB_scores)

[0.5105606  0.57530596 0.4789775  0.81393742 0.68690159 0.74573092]


In [14]:
import numpy as np
NB_cv_mean = np.mean(NB_scores)
print('Mean score : ', NB_cv_mean)

Mean score :  0.6352356653825152


In [15]:
#Random forest

In [16]:
from sklearn.ensemble import RandomForestClassifier
RF = RandomForestClassifier()

In [17]:
rf_scores = cross_val_score(RF, x, y, cv=6, scoring='accuracy')

In [18]:
rf_scores.mean()

0.9105271492857958

In [19]:
print(rf_scores)

[0.91393604 0.92933281 0.85343466 0.93268187 0.94196032 0.89181719]


In [20]:
rf_cv_mean = np.mean(rf_scores)

print('forest Mean score : ', rf_cv_mean)

forest Mean score :  0.9105271492857958


In [21]:
#desicion tree

In [22]:
from sklearn.tree import DecisionTreeClassifier
clf_gini = DecisionTreeClassifier()

In [23]:
dt_scores = cross_val_score(clf_gini, x, y, cv=6, scoring='accuracy')

In [24]:
dt_scores.mean()

0.8757840083431848

In [25]:
print(dt_scores)

[0.87080537 0.90416502 0.81829846 0.90247754 0.90405686 0.8549008 ]


In [26]:
dt_cv_mean = np.mean(dt_scores)

print('dt Mean score : ', dt_cv_mean)

dt Mean score :  0.8757840083431848


In [27]:
#gradient boosting

In [28]:
from sklearn.ensemble import GradientBoostingClassifier
import time

In [29]:
gb = GradientBoostingClassifier()

In [30]:
start_gb = time.time()

gb_scores = cross_val_score(gb, x, y, cv=6, scoring='accuracy')
print(gb_scores.mean())

end_gb =time.time()
gb_time = (end_gb-start_gb)/60
print('The time taken for the classifier for 6 fold cross validation is ' + str(gb_time))

0.9156267577586622
The time taken for the classifier for 6 fold cross validation is 4.941470317045847


In [31]:
print(gb_scores)

[0.92716147 0.93347809 0.85126332 0.93524825 0.9445267  0.90208272]


In [32]:
gb_cv_mean = np.mean(gb_scores)
print('gb Mean score : ', gb_cv_mean)

gb Mean score :  0.9156267577586622
